name: deploy-auth

on:
  push:
    branches: 
      - main
    paths:
      - 'auth/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ticketing-dev-395902
        
      - name: Deploy via GCS
        run: |
          gsutil -m rm -rf gs://ticketing-dev-395902_cloudbuild/* || echo "$?"
          gsutil -m cp -r * gs://ticketing-dev-395902_cloudbuild/
      - run: kubectl rollout restart deployment auth-depl
