name: deploy-auth

on:
  push:
    branches: 
      - main
    paths:
      - 'auth/**'
      - .github/workflows/deploy-auth.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker
      - run: gcloud auth application-default login
      - name: Build API
        run: gcloud builds submit --tag us.gcr.io/ticketing-dev-395902/auth .
      - name: Deploy API
        run: gcloud run deploy api --image us.gcr.io/ticketing-dev-395902/auth --platform managed --zone=southamerica-east1-a
