name: deploy-manifests

on:
  push:
    branches: 
      - main
    paths:
      - 'infra/**'
      - .github/workflows/deploy-manifests.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          
      - name: Authenticate Google Cloud SDK
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > /tmp/gcp-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json

      - name: Deploy to GKE
        run: gcloud container clusters get-credentials ticketing-dev --zone=southamerica-east1-a
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
